### ISSUE TITLE
Package fails to compile on Linux 18.04

### ISSUE THREAD

**Issue by The-SS** [omwdunkley/Qualisys2Ros#1]
Hi,
When trying to build this package on Linux 16.04, everything is fine. However, on Linux 18.04, an error occurs.
```
.../RTProtocol.cpp:451:54: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
                 if (ReceiveRTPacket(eType, false) == false)
```
I simply typecasted  ReceiveRTPacket to bool as such: ` if ((bool)ReceiveRTPacket(eType, false) == false)` and the package built correctly.
I don't have a Qualisys system to make sure this works though.
